name: matrix
on:
  # schedule: [ cron: '0 5 * * *' ] # every day at 5am UTC
  workflow_dispatch:

jobs:
  build:
    env:
      BASE_OCI_REF: "ghcr.io/${{ github.repository_owner }}/"
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KERNEL_RPM_VERSION: "1000" # Bump this to rebuild everything
    permissions:
      packages: write # to write to ghcr.io
      contents: write # to commit to the repo
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false # let other jobs try to complete if one fails
      matrix:
        include: # To build against a specific EL_MINOR_VERSION eg 7, use EL_VERSION to override "8.7"; otherwise uses latest 
          - { id: "el8-6.1.y-kvm", env: { EL_MAJOR_VERSION: "8", KERNEL_MAJOR: "6", KERNEL_MINOR: "1", FLAVOR: "kvm" } }
          - { id: "el9-6.1.y-kvm", env: { EL_MAJOR_VERSION: "9", KERNEL_MAJOR: "6", KERNEL_MINOR: "1", FLAVOR: "kvm" } }
          - { id: "el8-6.1.y-generic", env: { EL_MAJOR_VERSION: "8", KERNEL_MAJOR: "6", KERNEL_MINOR: "1", FLAVOR: "generic" } }
    name: "${{ matrix.id }}"
    steps:
      - name: cleanup GHA hosted runner
        run: |
          # Workaround to provide additional free space for building.
          #   https://github.com/actions/virtual-environments/issues/2840
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Checkout build repo
        uses: actions/checkout@v4

      - name: Docker Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }} # GitHub username or org
          password: ${{ secrets.GITHUB_TOKEN }}    # GitHub actions builtin token. repo has to have pkg access.

      - name: Actually process ${{matrix.id}}
        id: magic
        env: ${{ matrix.env }} # this gets combined with the job-wide env's like BASE_OCI_REF
        run: |
          bash kernel.sh checkbuildandpush

      - name: Commit changes to the examples directory # @TODO not really used, "yet"
        run: |
          git config --global user.name "GHA workflow"
          git config --global user.email "workflow@github.com"
          git pull || true # repo might have changed since we started, avoid conflicts
          git add examples || true
          git commit -m "Update examples for ${{ matrix.id }}" || true
          git push || true
  
  # release gets called when all build jobs are done
  release: # @TODO not really used "yet"
    needs: [ build ] # depend on the previous jobs...
    if: "${{ !cancelled() }}" # ... but run even if (some of) them failed, but not if job was cancelled
    runs-on: ubuntu-latest
    steps:
      - name: List current dir
        run: |
          ls -lahtR
